import Head from "next/head";
import Image from "next/image";
import React from "react";
import { useState } from "react";
import Game from "../components/game";

import User from "../components/user";

import styles from "../styles/Home.module.css";

export default function Home() {
  const [gameStart, setGameStart] = useState(false);
  const [user, setUser] = useState("");
  const [wins, setWins] = useState(0);
  const [losers, setLosers] = useState(0);
  const [chance, setChance] = useState(true);
  const [x, isX] = useState(false);
  const [positions, setPositions] = useState([""]);
  const [count, setCount] = useState(0);

  return (
    <div className="bg-gray-900  w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" flex justify-center items-center  w-screen h-screen">
        <div className="flex justify-center items-center">
          {!gameStart && (
            <User
              setGameStart={setGameStart}
              gameStart={gameStart}
              user={user}
              setUser={setUser}
            ></User>
          )}
        </div>

        {gameStart && (
          <div className="flex flex-1 justify-start content-start w-screen h-screen p-10">
            <Game
              user={user}
              setUser={setUser}
              wins={wins}
              setWins={setWins}
              losers={losers}
              setLosers={setLosers}
              positions={positions}
              setPositions={setPositions}
              chance={chance}
              setChance={setChance}
              count={count}
              setCount={setCount}
              x={x}
              isX={isX}
            ></Game>
          </div>
        )}
      </div>
    </div>
  );
}
