import Head from "next/head";
import Image from "next/image";
import React from "react";
import { useState } from "react";
import Game from "../components/game";
import Logo from "../components/logo";
import Score from "../components/score";

import User from "../components/user";

import styles from "../styles/Home.module.css";

export default function Home() {
  const [gameStart, setGameStart] = useState(false);
  const [user, setUser] = useState("");
  const [wins, setWins] = useState(0);
  const [losers, setLosers] = useState(0);
  const [chance, setChance] = useState(true);
  const [x, isX] = useState(false);
  const [positions, setPositions] = useState([""]);
  const [count, setCount] = useState(0);

  return (
    <div className="bg-gray-900  w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" flex justify-center items-center  w-screen h-screen">
        {!gameStart && (
          <div className="flex flex-col">
            <Logo></Logo>
            <div className="flex justify-center items-center">
              <User
                setGameStart={setGameStart}
                gameStart={gameStart}
                user={user}
                setUser={setUser}
              ></User>
            </div>
          </div>
        )}

        {gameStart && (
          <div className="flex flex-1 justify-start content-start w-screen h-screen p-7  ">
            <Score
              setLosers={setLosers}
              losers={losers}
              wins={wins}
              setUser={setUser}
              setWins={setWins}
              user={user}
            ></Score>
            <Game user={user} wins={wins} losers={losers}></Game>
          </div>
        )}
      </div>
    </div>
  );
}
